token: ''

bot:
  plugins:
    - aetherya.plugins.core
    - aetherya.plugins.moderation
    - aetherya.plugins.music
    - aetherya.plugins.utilities
    - aetherya.plugins.events
    - aetherya.plugins.social
  commands_require_mention: false
  # commands_prefix: '!'